### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by AliKhoda** [gima/pgkiss#3]
The first time I clone a repository with this, it works perfectly. As soon as I do a push, it becomes impossible to clone it again and I get timeout. However I can push from the previous cloned version.

Please let me know if I can provide debugging information.

**Comment by gima** [comment]
The problem that you are describing it not caused by this repository. It is either a transient problem with GitHub or a problem with the local git installation or it's usage.

**Comment by AliKhoda** [comment]
Thank you for the quick response. It works with CGI without a problem.
